MiniBlogApp: MiniBlogApp.Tests.ServiceTests.UserServiceTests Class Reference
MiniBlogApp.Tests.ServiceTests.UserServiceTests Class Reference
Contains unit tests for basic UserService functionality.
Public Member Functions
void Authenticate_ShouldReturnUser_WhenCredentialsAreCorrect ()
Tests successful authentication with correct credentials.
void Authenticate_ShouldReturnNull_WhenCredentialsAreIncorrect ()
Tests failed authentication with incorrect credentials.
void GetAll_ShouldReturnAllUsers ()
Tests that GetAll() returns all predefined users.
Private Attributes
readonly UserService _userService = new()
Instance of the UserService under test.
Static Private Attributes
const string CorrectUsername = "serhii"
Correct username for authentication tests.
const string CorrectPassword = "1234"
Correct password for authentication tests.
const string WrongPassword = "wrongpassword"
Incorrect password to test failed authentication.
const string AnotherUser = "maria"
Another predefined username to verify GetAll() functionality.
Detailed Description
Contains unit tests for basic UserService functionality.
Focuses on verifying authentication and user retrieval under normal conditions using predefined users.
Definition at line 25 of file UserServiceTests.cs.
Member Function Documentation
Authenticate_ShouldReturnNull_WhenCredentialsAreIncorrect()
void MiniBlogApp.Tests.ServiceTests.UserServiceTests.Authenticate_ShouldReturnNull_WhenCredentialsAreIncorrect ()
Tests failed authentication with incorrect credentials.
Confirms that Authenticate returns null if the password does not match the stored value for the given username.
Definition at line 63 of file UserServiceTests.cs.
        {
            var user = _userService.Authenticate(CorrectUsername, WrongPassword);
            Assert.Null(user);
        }
Authenticate_ShouldReturnUser_WhenCredentialsAreCorrect()
void MiniBlogApp.Tests.ServiceTests.UserServiceTests.Authenticate_ShouldReturnUser_WhenCredentialsAreCorrect ()
Tests successful authentication with correct credentials.
Ensures that when both username and password match a predefined user, the Authenticate method returns a valid BlogUser instance with the expected username.
Definition at line 49 of file UserServiceTests.cs.
        {
            var user = _userService.Authenticate(CorrectUsername, CorrectPassword);
            Assert.NotNull(user);
            Assert.Equal(CorrectUsername, user.Username);
        }
GetAll_ShouldReturnAllUsers()
void MiniBlogApp.Tests.ServiceTests.UserServiceTests.GetAll_ShouldReturnAllUsers ()
Tests that GetAll() returns all predefined users.
Verifies that the returned collection contains both "serhii" and "maria", confirming that the in-memory user store is correctly exposed by the service.
Definition at line 77 of file UserServiceTests.cs.
        {
            var users = _userService.GetAll();
            Assert.NotEmpty(users);
            Assert.Contains(users, u => u.Username == CorrectUsername);
            Assert.Contains(users, u => u.Username == AnotherUser);
        }
Member Data Documentation
_userService
readonly UserService MiniBlogApp.Tests.ServiceTests.UserServiceTests._userService = new() private
Instance of the UserService under test.
Definition at line 28 of file UserServiceTests.cs.
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceTests.Authenticate_ShouldReturnNull_WhenCredentialsAreIncorrect(), MiniBlogApp.Tests.ServiceTests.UserServiceTests.Authenticate_ShouldReturnUser_WhenCredentialsAreCorrect(), and MiniBlogApp.Tests.ServiceTests.UserServiceTests.GetAll_ShouldReturnAllUsers().
AnotherUser
const string MiniBlogApp.Tests.ServiceTests.UserServiceTests.AnotherUser = "maria" static private
Another predefined username to verify GetAll() functionality.
Definition at line 40 of file UserServiceTests.cs.
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceTests.GetAll_ShouldReturnAllUsers().
CorrectPassword
const string MiniBlogApp.Tests.ServiceTests.UserServiceTests.CorrectPassword = "1234" static private
Correct password for authentication tests.
Definition at line 34 of file UserServiceTests.cs.
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceTests.Authenticate_ShouldReturnUser_WhenCredentialsAreCorrect().
CorrectUsername
const string MiniBlogApp.Tests.ServiceTests.UserServiceTests.CorrectUsername = "serhii" static private
Correct username for authentication tests.
Definition at line 31 of file UserServiceTests.cs.
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceTests.Authenticate_ShouldReturnNull_WhenCredentialsAreIncorrect(), MiniBlogApp.Tests.ServiceTests.UserServiceTests.Authenticate_ShouldReturnUser_WhenCredentialsAreCorrect(), and MiniBlogApp.Tests.ServiceTests.UserServiceTests.GetAll_ShouldReturnAllUsers().
WrongPassword
const string MiniBlogApp.Tests.ServiceTests.UserServiceTests.WrongPassword = "wrongpassword" static private
Incorrect password to test failed authentication.
Definition at line 37 of file UserServiceTests.cs.
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceTests.Authenticate_ShouldReturnNull_WhenCredentialsAreIncorrect().
The documentation for this class was generated from the following file:
/home/runner/work/MiniBlogApp/MiniBlogApp/MiniBlogApp.Tests/ServiceTests/UserServiceTests.cs