MiniBlogApp: MiniBlogApp.Services.PostAnalyzer< T > Class Template Reference
MiniBlogApp.Services.PostAnalyzer< T > Class Template Reference
Public Member Functions
string Analyze (T post)
Detailed Description
Type Constraints
T : Post
Definition at line 5 of file PostAnalysisService.cs.
Member Function Documentation
Analyze()
string MiniBlogApp.Services.PostAnalyzer< T >.Analyze (T post)
Definition at line 7 of file PostAnalysisService.cs.
        {
            var title = post.Title ?? "без назви";
            var author = post.Author ?? "невідомий";
            var likesCount = post.Likes?.Count ?? 0;
            var commentsCount = post.Comments?.Count ?? 0;
            return $"Пост '{title}' створений користувачем {author}, має {likesCount} лайків і {commentsCount} коментарів.";
        }
Referenced by MiniBlogApp.Tests.UtilsTests.PostAnalyzerTests.Analyze_ShouldHandlePostWithManyLikesAndComments(), MiniBlogApp.Tests.UtilsTests.PostAnalyzerTests.Analyze_ShouldHandlePostWithNullAuthorOrTitle(), and MiniBlogApp.Pages.PostAnalyticsModel.OnGet().
The documentation for this class was generated from the following file:
/home/runner/work/MiniBlogApp/MiniBlogApp/MiniBlogApp/Services/PostAnalysisService.cs