MiniBlogApp: MiniBlogApp.Services.LoggerService Class Reference
MiniBlogApp.Services.LoggerService Class Reference
Public Member Functions
void AddLog (ILogEntry entry)
List< string > GetLogs ()
void ClearAll ()
Private Attributes
readonly object _lock = new object()
readonly List< string > _logs = new()
Detailed Description
Definition at line 80 of file LoggerService.cs.
Member Function Documentation
AddLog()
void MiniBlogApp.Services.LoggerService.AddLog (ILogEntry entry)
Implements MiniBlogApp.Services.IActivityLogger.
Definition at line 85 of file LoggerService.cs.
        {
            lock (_lock)
            {
                // Тут викликається наш Шаблонний метод GetMessage()
                _logs.Insert(0, entry.GetMessage());
            }
        }
Referenced by LoggerServiceAdvancedTests.AddLog_ShouldStoreMessagesForDifferentActions().
ClearAll()
void MiniBlogApp.Services.LoggerService.ClearAll ()
Implements MiniBlogApp.Services.IActivityLogger.
Definition at line 102 of file LoggerService.cs.
        {
            lock (_lock)
            {
                _logs.Clear();
            }
        }
Referenced by MiniBlogApp.Tests.ServiceTests.BlogStorageAddLikeTests.BlogStorageAddLikeTests(), MiniBlogApp.Tests.ServiceTests.BlogStorageAddPostTests.BlogStorageAddPostTests(), MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.BlogStorageAdvancedTests(), MiniBlogApp.Tests.ServiceTests.BlogStorageEdgeCaseTests.BlogStorageEdgeCaseTests(), and LoggerServiceAdvancedTests.LoggerServiceAdvancedTests().
GetLogs()
List< string > MiniBlogApp.Services.LoggerService.GetLogs ()
Implements MiniBlogApp.Services.IActivityLogger.
Definition at line 94 of file LoggerService.cs.
        {
            lock (_lock)
            {
                return _logs.ToList();
            }
        }
Referenced by MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.AddComment_ShouldAddToPostAndLogMessage(), MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.AddLike_ShouldLogMessageOnlyOncePerUser(), LoggerServiceAdvancedTests.AddLog_ShouldStoreMessagesForDifferentActions(), and MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.AddPost_ShouldAssignUniqueIdsAndLogMessages().
Member Data Documentation
_lock
readonly object MiniBlogApp.Services.LoggerService._lock = new object() private
Definition at line 82 of file LoggerService.cs.
Referenced by MiniBlogApp.Services.LoggerService.AddLog(), MiniBlogApp.Services.LoggerService.ClearAll(), and MiniBlogApp.Services.LoggerService.GetLogs().
_logs
readonly List<string> MiniBlogApp.Services.LoggerService._logs = new() private
Definition at line 83 of file LoggerService.cs.
Referenced by MiniBlogApp.Services.LoggerService.AddLog(), MiniBlogApp.Services.LoggerService.ClearAll(), and MiniBlogApp.Services.LoggerService.GetLogs().
The documentation for this class was generated from the following file:
/home/runner/work/MiniBlogApp/MiniBlogApp/MiniBlogApp/Services/LoggerService.cs