MiniBlogApp: MiniBlogApp.Builders.PostBuilder Class Reference
MiniBlogApp.Builders.PostBuilder Class Reference
Конкретна реалізація патерну Builder для класу Post.
Public Member Functions
PostBuilder ()
void Reset ()
IPostBuilder SetTitle (string title)
IPostBuilder SetContent (string content)
IPostBuilder SetAuthor (string authorName)
Post Build ()
Private Attributes
Post _post = new Post()
Detailed Description
Конкретна реалізація патерну Builder для класу Post.
Дозволяє покроково конструювати об'єкт поста.
Definition at line 10 of file PostBuilder.cs.
Constructor & Destructor Documentation
PostBuilder()
MiniBlogApp.Builders.PostBuilder.PostBuilder ()
Definition at line 15 of file PostBuilder.cs.
        {
            Reset();
        }
Member Function Documentation
Build()
Post MiniBlogApp.Builders.PostBuilder.Build ()
Implements MiniBlogApp.Builders.IPostBuilder.
Definition at line 45 of file PostBuilder.cs.
        {
            Post result = _post;
            // Після виклику Build(), будівельник готовий до створення нового поста
            Reset();
            return result;
        }
Reset()
void MiniBlogApp.Builders.PostBuilder.Reset ()
Definition at line 20 of file PostBuilder.cs.
        {
            _post = new Post();
            _post.CreatedAt = DateTime.UtcNow; // Встановлюємо дату за замовчуванням
        }
Referenced by MiniBlogApp.Builders.PostBuilder.Build(), and MiniBlogApp.Builders.PostBuilder.PostBuilder().
SetAuthor()
IPostBuilder MiniBlogApp.Builders.PostBuilder.SetAuthor (string authorName)
Implements MiniBlogApp.Builders.IPostBuilder.
Definition at line 39 of file PostBuilder.cs.
        {
            _post.Author = authorName;
            return this;
        }
SetContent()
IPostBuilder MiniBlogApp.Builders.PostBuilder.SetContent (string content)
Implements MiniBlogApp.Builders.IPostBuilder.
Definition at line 32 of file PostBuilder.cs.
        {
            _post.Content = content;
            return this;
        }
SetTitle()
IPostBuilder MiniBlogApp.Builders.PostBuilder.SetTitle (string title)
Implements MiniBlogApp.Builders.IPostBuilder.
Definition at line 26 of file PostBuilder.cs.
        {
            _post.Title = title;
            return this;
        }
Member Data Documentation
_post
Post MiniBlogApp.Builders.PostBuilder._post = new Post() private
Definition at line 13 of file PostBuilder.cs.
Referenced by MiniBlogApp.Builders.PostBuilder.Build(), and MiniBlogApp.Builders.PostBuilder.Reset().
The documentation for this class was generated from the following file:
/home/runner/work/MiniBlogApp/MiniBlogApp/MiniBlogApp/Builders/PostBuilder.cs