MiniBlogApp: MiniBlogApp.Proxies.CachedBlogStorageProxy Class Reference
MiniBlogApp.Proxies.CachedBlogStorageProxy Class Reference
ПАТЕРН PROXY (Замісник - Кешуючий).
Public Member Functions
CachedBlogStorageProxy (IBlogStorage realStorage)
Post? GetPostById (int id)
Post AddPost (Post post)
Post? UpdatePost (int id, string title, string content)
void DeletePost (int id)
void AddLike (int postId, string username)
void RemoveLike (int postId, string username)
void AddComment (int postId, string author, string text)
void AddReply (int postId, int parentCommentId, string author, string text)
IEnumerable< Post > GetAllPosts ()
IEnumerable< Post > GetPostsByUser (string username)
IEnumerable< Post > GetAllPosts (IPostSortStrategy sortStrategy)
Properties
List< Post > Posts [get]
Properties inherited from MiniBlogApp.Services.IBlogStorage
Private Attributes
readonly IBlogStorage _realStorage
readonly Dictionary< int, Post > _postCache = new()
Detailed Description
ПАТЕРН PROXY (Замісник - Кешуючий).
Контролює доступ до основного сховища (IBlogStorage). Зберігає результати запитів у пам'яті (кеші), щоб зменшити навантаження на "базу даних" при повторних запитах.
Definition at line 16 of file CachedBlogStorageProxy.cs.
Constructor & Destructor Documentation
CachedBlogStorageProxy()
MiniBlogApp.Proxies.CachedBlogStorageProxy.CachedBlogStorageProxy (IBlogStorage realStorage)
Definition at line 23 of file CachedBlogStorageProxy.cs.
        {
            _realStorage = realStorage;
        }
Member Function Documentation
AddComment()
void MiniBlogApp.Proxies.CachedBlogStorageProxy.AddComment (int postId, string author, string text)
Implements MiniBlogApp.Services.IBlogStorage.
AddLike()
void MiniBlogApp.Proxies.CachedBlogStorageProxy.AddLike (int postId, string username)
Implements MiniBlogApp.Services.IBlogStorage.
AddPost()
Post MiniBlogApp.Proxies.CachedBlogStorageProxy.AddPost (Post post)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 57 of file CachedBlogStorageProxy.cs.
        {
            _postCache.Clear(); // Дані змінилися, чистимо кеш
            return _realStorage.AddPost(post);
        }
AddReply()
void MiniBlogApp.Proxies.CachedBlogStorageProxy.AddReply (int postId, int parentCommentId, string author, string text)
Implements MiniBlogApp.Services.IBlogStorage.
DeletePost()
void MiniBlogApp.Proxies.CachedBlogStorageProxy.DeletePost (int id)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 69 of file CachedBlogStorageProxy.cs.
        {
            _postCache.Clear(); // Дані змінилися, чистимо кеш
            _realStorage.DeletePost(id);
        }
GetAllPosts() [1/2]
IEnumerable< Post > MiniBlogApp.Proxies.CachedBlogStorageProxy.GetAllPosts ()
Implements MiniBlogApp.Services.IBlogStorage.
GetAllPosts() [2/2]
IEnumerable< Post > MiniBlogApp.Proxies.CachedBlogStorageProxy.GetAllPosts (IPostSortStrategy sortStrategy)
Implements MiniBlogApp.Services.IBlogStorage.
GetPostById()
Post? MiniBlogApp.Proxies.CachedBlogStorageProxy.GetPostById (int id)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 32 of file CachedBlogStorageProxy.cs.
        {
            // 1. Спочатку перевіряємо, чи є пост у нашому швидкому кеші
            if (_postCache.ContainsKey(id))
            {
                // Повертаємо з кешу (швидко!)
                return _postCache[id];
            }
            // 2. Якщо в кеші немає, йдемо до реального сховища (повільно)
            var post = _realStorage.GetPostById(id);
            // 3. Зберігаємо результат у кеш для наступних разів
            if (post != null)
            {
                _postCache[id] = post;
            }
            return post;
        }
GetPostsByUser()
IEnumerable< Post > MiniBlogApp.Proxies.CachedBlogStorageProxy.GetPostsByUser (string username)
Implements MiniBlogApp.Services.IBlogStorage.
RemoveLike()
void MiniBlogApp.Proxies.CachedBlogStorageProxy.RemoveLike (int postId, string username)
Implements MiniBlogApp.Services.IBlogStorage.
UpdatePost()
Post? MiniBlogApp.Proxies.CachedBlogStorageProxy.UpdatePost (int id, string title, string content)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 63 of file CachedBlogStorageProxy.cs.
        {
            _postCache.Clear(); // Дані змінилися, чистимо кеш
            return _realStorage.UpdatePost(id, title, content);
        }
Member Data Documentation
_postCache
readonly Dictionary<int, Post> MiniBlogApp.Proxies.CachedBlogStorageProxy._postCache = new() private
Definition at line 21 of file CachedBlogStorageProxy.cs.
Referenced by MiniBlogApp.Proxies.CachedBlogStorageProxy.AddPost(), MiniBlogApp.Proxies.CachedBlogStorageProxy.DeletePost(), MiniBlogApp.Proxies.CachedBlogStorageProxy.GetPostById(), and MiniBlogApp.Proxies.CachedBlogStorageProxy.UpdatePost().
_realStorage
readonly IBlogStorage MiniBlogApp.Proxies.CachedBlogStorageProxy._realStorage private
Definition at line 18 of file CachedBlogStorageProxy.cs.
Referenced by MiniBlogApp.Proxies.CachedBlogStorageProxy.AddPost(), MiniBlogApp.Proxies.CachedBlogStorageProxy.CachedBlogStorageProxy(), MiniBlogApp.Proxies.CachedBlogStorageProxy.DeletePost(), MiniBlogApp.Proxies.CachedBlogStorageProxy.GetPostById(), and MiniBlogApp.Proxies.CachedBlogStorageProxy.UpdatePost().
Property Documentation
Posts
List<Post> MiniBlogApp.Proxies.CachedBlogStorageProxy.Posts get
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 28 of file CachedBlogStorageProxy.cs.
The documentation for this class was generated from the following file:
/home/runner/work/MiniBlogApp/MiniBlogApp/MiniBlogApp/Proxies/CachedBlogStorageProxy.cs