MiniBlogApp: MiniBlogApp.Services.ConcurrentBlogStorage Class Reference
MiniBlogApp.Services.ConcurrentBlogStorage Class Reference
Потокобезпечне сховище дописів на основі ReaderWriterLockSlim.
Public Member Functions
Post AddPost (Post post)
Post? UpdatePost (int id, string title, string content)
void DeletePost (int id)
IEnumerable< Post > GetAllPosts ()
IEnumerable< Post > GetPostsByUser (string username)
Post? GetPostById (int id)
void AddLike (int postId, string username)
void RemoveLike (int postId, string username)
void AddComment (int postId, string author, string text)
void AddReply (int postId, int parentCommentId, string author, string text)
IEnumerable< Post > GetAllPosts (IPostSortStrategy sortStrategy)
Properties
List< Post > Posts [get]
Properties inherited from MiniBlogApp.Services.IBlogStorage
Private Attributes
readonly List< Post > _posts = new List<Post>()
readonly ReaderWriterLockSlim _rwLock = new ReaderWriterLockSlim()
int _nextPostId = 1
int _nextCommentId = 1
Detailed Description
Потокобезпечне сховище дописів на основі ReaderWriterLockSlim.
Дозволяє паралельне читання багатьма потоками, але надає ексклюзивний доступ під час запису.
Definition at line 14 of file ConcurrentBlogStorage.cs.
Member Function Documentation
AddComment()
void MiniBlogApp.Services.ConcurrentBlogStorage.AddComment (int postId, string author, string text)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 171 of file ConcurrentBlogStorage.cs.
        {
            _rwLock.EnterWriteLock();
            try
            {
                var post = _posts.FirstOrDefault(p => p.Id == postId);
                if (post != null)
                {
                    post.Comments ??= new List<Comment>(); // Тут List<Comment>
                    post.Comments.Add(new Comment
                    {
                        Id = _nextCommentId++,
                        Author = author,
                        Text = text,
                        Replies = new List<ICommentComponent>() // А ось тут ICommentComponent
                    });
                }
            }
            finally
            {
                _rwLock.ExitWriteLock();
            }
        }
AddLike()
void MiniBlogApp.Services.ConcurrentBlogStorage.AddLike (int postId, string username)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 129 of file ConcurrentBlogStorage.cs.
        {
            _rwLock.EnterWriteLock();
            try
            {
                var post = _posts.FirstOrDefault(p => p.Id == postId);
                if (post != null)
                {
                    post.Likes ??= new List<Like>();
                    if (!post.Likes.Any(l => l.Username == username))
                    {
                        post.Likes.Add(new Like { Username = username });
                    }
                }
            }
            finally
            {
                _rwLock.ExitWriteLock();
            }
        }
AddPost()
Post MiniBlogApp.Services.ConcurrentBlogStorage.AddPost (Post post)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 37 of file ConcurrentBlogStorage.cs.
        {
            _rwLock.EnterWriteLock();
            try
            {
                post.Id = _nextPostId++;
                post.Likes ??= new List<Like>();
                post.Comments ??= new List<Comment>(); // Тут List<Comment>
                _posts.Add(post);
                return post;
            }
            finally
            {
                _rwLock.ExitWriteLock();
            }
        }
AddReply()
void MiniBlogApp.Services.ConcurrentBlogStorage.AddReply (int postId, int parentCommentId, string author, string text)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 195 of file ConcurrentBlogStorage.cs.
        {
            _rwLock.EnterWriteLock();
            try
            {
                var post = _posts.FirstOrDefault(p => p.Id == postId);
                if (post != null && post.Comments != null)
                {
                    var parentComment = post.Comments.FirstOrDefault(c => c.Id == parentCommentId);
                    if (parentComment != null)
                    {
                        parentComment.Replies ??= new List<ICommentComponent>(); // Тут ICommentComponent
                        parentComment.Replies.Add(new Comment
{
                            Id = _nextCommentId++,
                            Author = author,
                            Text = text,
                            Replies = new List<ICommentComponent>()
                        });
                    }
                }
            }
            finally
            {
                _rwLock.ExitWriteLock();
            }
        }
DeletePost()
void MiniBlogApp.Services.ConcurrentBlogStorage.DeletePost (int id)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 73 of file ConcurrentBlogStorage.cs.
        {
            _rwLock.EnterWriteLock();
            try
            {
                var post = _posts.FirstOrDefault(p => p.Id == id);
                if (post != null)
                {
                    _posts.Remove(post);
                }
            }
            finally
            {
                _rwLock.ExitWriteLock();
            }
        }
GetAllPosts() [1/2]
IEnumerable< Post > MiniBlogApp.Services.ConcurrentBlogStorage.GetAllPosts ()
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 90 of file ConcurrentBlogStorage.cs.
        {
            _rwLock.EnterReadLock();
            try
            {
                return _posts.ToList();
            }
            finally
            {
                _rwLock.ExitReadLock();
            }
        }
GetAllPosts() [2/2]
IEnumerable< Post > MiniBlogApp.Services.ConcurrentBlogStorage.GetAllPosts (IPostSortStrategy sortStrategy)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 223 of file ConcurrentBlogStorage.cs.
        {
            _rwLock.EnterReadLock();
            List<Post> snapshot;
            try
            {
                snapshot = _posts.ToList();
            }
            finally
            {
                _rwLock.ExitReadLock();
            }
            return sortStrategy.Sort(snapshot);
        }
GetPostById()
Post? MiniBlogApp.Services.ConcurrentBlogStorage.GetPostById (int id)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 116 of file ConcurrentBlogStorage.cs.
        {
            _rwLock.EnterReadLock();
            try
            {
                return _posts.FirstOrDefault(p => p.Id == id);
            }
            finally
            {
                _rwLock.ExitReadLock();
            }
        }
GetPostsByUser()
IEnumerable< Post > MiniBlogApp.Services.ConcurrentBlogStorage.GetPostsByUser (string username)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 103 of file ConcurrentBlogStorage.cs.
        {
            _rwLock.EnterReadLock();
            try
            {
                return _posts.Where(p => p.Author == username).ToList();
            }
            finally
            {
                _rwLock.ExitReadLock();
            }
        }
RemoveLike()
void MiniBlogApp.Services.ConcurrentBlogStorage.RemoveLike (int postId, string username)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 150 of file ConcurrentBlogStorage.cs.
        {
            _rwLock.EnterWriteLock();
            try
            {
                var post = _posts.FirstOrDefault(p => p.Id == postId);
                if (post != null && post.Likes != null)
                {
                    var like = post.Likes.FirstOrDefault(l => l.Username == username);
                    if (like != null)
                    {
                        post.Likes.Remove(like);
                    }
                }
            }
            finally
            {
                _rwLock.ExitWriteLock();
            }
        }
UpdatePost()
Post? MiniBlogApp.Services.ConcurrentBlogStorage.UpdatePost (int id, string title, string content)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 54 of file ConcurrentBlogStorage.cs.
        {
            _rwLock.EnterWriteLock();
            try
            {
                var post = _posts.FirstOrDefault(p => p.Id == id);
                if (post != null)
                {
                    post.Title = title;
                    post.Content = content;
                }
                return post;
            }
            finally
            {
                _rwLock.ExitWriteLock();
            }
        }
Member Data Documentation
_nextCommentId
int MiniBlogApp.Services.ConcurrentBlogStorage._nextCommentId = 1 private
Definition at line 19 of file ConcurrentBlogStorage.cs.
Referenced by MiniBlogApp.Services.ConcurrentBlogStorage.AddComment(), and MiniBlogApp.Services.ConcurrentBlogStorage.AddReply().
_nextPostId
int MiniBlogApp.Services.ConcurrentBlogStorage._nextPostId = 1 private
Definition at line 18 of file ConcurrentBlogStorage.cs.
Referenced by MiniBlogApp.Services.ConcurrentBlogStorage.AddPost().
_posts
readonly List<Post> MiniBlogApp.Services.ConcurrentBlogStorage._posts = new List<Post>() private
Definition at line 16 of file ConcurrentBlogStorage.cs.
Referenced by MiniBlogApp.Services.ConcurrentBlogStorage.AddComment(), MiniBlogApp.Services.ConcurrentBlogStorage.AddLike(), MiniBlogApp.Services.ConcurrentBlogStorage.AddPost(), MiniBlogApp.Services.ConcurrentBlogStorage.AddReply(), MiniBlogApp.Services.ConcurrentBlogStorage.DeletePost(), MiniBlogApp.Services.ConcurrentBlogStorage.GetAllPosts(), MiniBlogApp.Services.ConcurrentBlogStorage.GetAllPosts(), MiniBlogApp.Services.ConcurrentBlogStorage.GetPostById(), MiniBlogApp.Services.ConcurrentBlogStorage.GetPostsByUser(), MiniBlogApp.Services.ConcurrentBlogStorage.RemoveLike(), and MiniBlogApp.Services.ConcurrentBlogStorage.UpdatePost().
_rwLock
readonly ReaderWriterLockSlim MiniBlogApp.Services.ConcurrentBlogStorage._rwLock = new ReaderWriterLockSlim() private
Definition at line 17 of file ConcurrentBlogStorage.cs.
Referenced by MiniBlogApp.Services.ConcurrentBlogStorage.AddComment(), MiniBlogApp.Services.ConcurrentBlogStorage.AddLike(), MiniBlogApp.Services.ConcurrentBlogStorage.AddPost(), MiniBlogApp.Services.ConcurrentBlogStorage.AddReply(), MiniBlogApp.Services.ConcurrentBlogStorage.DeletePost(), MiniBlogApp.Services.ConcurrentBlogStorage.GetAllPosts(), MiniBlogApp.Services.ConcurrentBlogStorage.GetAllPosts(), MiniBlogApp.Services.ConcurrentBlogStorage.GetPostById(), MiniBlogApp.Services.ConcurrentBlogStorage.GetPostsByUser(), MiniBlogApp.Services.ConcurrentBlogStorage.RemoveLike(), and MiniBlogApp.Services.ConcurrentBlogStorage.UpdatePost().
Property Documentation
Posts
List<Post> MiniBlogApp.Services.ConcurrentBlogStorage.Posts get
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 21 of file ConcurrentBlogStorage.cs.
        {
            get
            {
                _rwLock.EnterReadLock();
                try
                {
                    return _posts.ToList();
                }
                finally
                {
                    _rwLock.ExitReadLock();
                }
            }
        }
The documentation for this class was generated from the following file:
/home/runner/work/MiniBlogApp/MiniBlogApp/MiniBlogApp/Services/ConcurrentBlogStorage.cs