MiniBlogApp: MiniBlogApp.Services.UserService Class Reference
MiniBlogApp.Services.UserService Class Reference
Public Member Functions
BlogUser? Authenticate (string username, string password)
IEnumerable< BlogUser > GetAll ()
Private Attributes
readonly List< BlogUser > _users
Detailed Description
Definition at line 5 of file UserService.cs.
Member Function Documentation
Authenticate()
BlogUser? MiniBlogApp.Services.UserService.Authenticate (string username, string password)
Definition at line 13 of file UserService.cs.
        {
            return _users.FirstOrDefault(u => u.Username == username && u.Password == password);
        }
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.Authenticate_ShouldBeCaseSensitive(), MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.Authenticate_ShouldFailForEmptyPassword(), MiniBlogApp.Tests.ServiceTests.UserServiceTests.Authenticate_ShouldReturnNull_WhenCredentialsAreIncorrect(), and MiniBlogApp.Tests.ServiceTests.UserServiceTests.Authenticate_ShouldReturnUser_WhenCredentialsAreCorrect().
GetAll()
IEnumerable< BlogUser > MiniBlogApp.Services.UserService.GetAll ()
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceTests.GetAll_ShouldReturnAllUsers(), and MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.GetAll_ShouldReturnAtLeastTwoUsers().
Member Data Documentation
_users
readonly List<BlogUser> MiniBlogApp.Services.UserService._users private
Initial value:
= new()
        {
            new BlogUser { Username = "serhii", Password = "1234" },
            new BlogUser { Username = "maria",  Password = "qwerty" }
        }
Definition at line 7 of file UserService.cs.
        {
            new BlogUser { Username = "serhii", Password = "1234" },
            new BlogUser { Username = "maria",  Password = "qwerty" }
        };
Referenced by MiniBlogApp.Services.UserService.Authenticate().
The documentation for this class was generated from the following file:
/home/runner/work/MiniBlogApp/MiniBlogApp/MiniBlogApp/Services/UserService.cs