MiniBlogApp: MiniBlogApp.Services.BlogStorage Class Reference
MiniBlogApp.Services.BlogStorage Class Reference
In-memory storage for blog posts and related operations.
Public Member Functions
BlogStorage ()
Post AddPost (Post post)
void AddComment (int postId, string author, string text)
void AddReply (int postId, int parentCommentId, string author, string text)
Post? UpdatePost (int id, string title, string content)
void DeletePost (int id)
IEnumerable< Post > GetAllPosts ()
IEnumerable< Post > GetPostsByUser (string username)
Post? GetPostById (int id)
void AddLike (int postId, string username)
IEnumerable< Post > GetAllPosts (IPostSortStrategy sortStrategy)
void RemoveLike (int postId, string username)
Properties
List< Post > Posts = new() [get]
Properties inherited from MiniBlogApp.Services.IBlogStorage
Private Member Functions
Comment? FindCommentRecursive (IEnumerable< ICommentComponent > components, int id)
Post? GetPostByIdInternal (int id)
Private Attributes
readonly object _lock = new object()
int _nextId = 1
Detailed Description
In-memory storage for blog posts and related operations.
Оновлено для підтримки патерну Composite (вкладені коментарі).
Definition at line 16 of file BlogStorage.cs.
Constructor & Destructor Documentation
BlogStorage()
MiniBlogApp.Services.BlogStorage.BlogStorage ()
Definition at line 22 of file BlogStorage.cs.
        {
        }
Member Function Documentation
AddComment()
void MiniBlogApp.Services.BlogStorage.AddComment (int postId, string author, string text)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 42 of file BlogStorage.cs.
        {
            lock (_lock)
            {
                var post = GetPostByIdInternal(postId);
                if (post == null) return;
                // Присвоюємо Id коментарю, щоб на нього можна було відповісти
                post.Comments.Add(new Comment
                {
                    Id = _nextId++,
                    Author = author,
                    Text = text
                });
            }
        }
Referenced by MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.AddComment_ShouldAddToPostAndLogMessage(), and MiniBlogApp.Tests.ServiceTests.BlogStorageEdgeCaseTests.AddComment_ShouldHandleEmptyText().
AddLike()
void MiniBlogApp.Services.BlogStorage.AddLike (int postId, string username)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 151 of file BlogStorage.cs.
        {
            lock (_lock)
            {
                var post = GetPostByIdInternal(postId);
                if (post == null) return;
                if (!post.Likes.Any(l => l.Username == username))
                {
                    post.Likes.Add(new Like { Username = username });
                }
            }
        }
Referenced by MiniBlogApp.Tests.ServiceTests.BlogStorageAddLikeTests.AddLike_ShouldAddLike_WhenUserHasNotLikedBefore(), MiniBlogApp.Tests.ServiceTests.BlogStorageEdgeCaseTests.AddLike_ShouldBeCaseSensitive_Usernames(), MiniBlogApp.Tests.ServiceTests.BlogStorageAddLikeTests.AddLike_ShouldDoNothing_WhenPostDoesNotExist(), MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.AddLike_ShouldLogMessageOnlyOncePerUser(), and MiniBlogApp.Tests.ServiceTests.BlogStorageAddLikeTests.AddLike_ShouldNotAddDuplicateLikes().
AddPost()
Post MiniBlogApp.Services.BlogStorage.AddPost (Post post)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 26 of file BlogStorage.cs.
        {
            lock (_lock)
            {
                post.Id = _nextId++;
                if (post.CreatedAt == default)
                {
                    post.CreatedAt = DateTime.Now;
                }
                Posts.Add(post);
                return post;
            }
        }
Referenced by MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.AddComment_ShouldAddToPostAndLogMessage(), MiniBlogApp.Tests.ServiceTests.BlogStorageEdgeCaseTests.AddComment_ShouldHandleEmptyText(), MiniBlogApp.Tests.ServiceTests.BlogStorageAddLikeTests.AddLike_ShouldAddLike_WhenUserHasNotLikedBefore(), MiniBlogApp.Tests.ServiceTests.BlogStorageEdgeCaseTests.AddLike_ShouldBeCaseSensitive_Usernames(), MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.AddLike_ShouldLogMessageOnlyOncePerUser(), MiniBlogApp.Tests.ServiceTests.BlogStorageAddLikeTests.AddLike_ShouldNotAddDuplicateLikes(), MiniBlogApp.Tests.ServiceTests.BlogStorageAddPostTests.AddPost_ShouldAddPostCorrectly(), MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.AddPost_ShouldAssignUniqueIdsAndLogMessages(), MiniBlogApp.Tests.ServiceTests.BlogStorageEdgeCaseTests.AddPost_ShouldHandleVeryLongContent(), MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.DeletePost_ShouldRemovePost(), and MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.UpdatePost_ShouldChangeContent().
AddReply()
void MiniBlogApp.Services.BlogStorage.AddReply (int postId, int parentCommentId, string author, string text)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 59 of file BlogStorage.cs.
        {
            lock (_lock)
            {
                var post = GetPostByIdInternal(postId);
                if (post == null) return;
                // Шукаємо батьківський коментар рекурсивно по всьому дереву
                var parentComment = FindCommentRecursive(post.Comments, parentCommentId);
                if (parentComment != null)
                {
                    parentComment.AddReply(new Comment
                    {
                        Id = _nextId++,
                        Author = author,
                        Text = text
                    });
                }
            }
        }
DeletePost()
void MiniBlogApp.Services.BlogStorage.DeletePost (int id)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 115 of file BlogStorage.cs.
        {
            lock (_lock)
            {
                var post = GetPostByIdInternal(id);
                if (post != null)
                    Posts.Remove(post);
            }
        }
Referenced by MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.DeletePost_ShouldRemovePost().
FindCommentRecursive()
Comment? MiniBlogApp.Services.BlogStorage.FindCommentRecursive (IEnumerable< ICommentComponent > components, int id) private
Definition at line 81 of file BlogStorage.cs.
        {
            foreach (var component in components)
            {
                if (component is Comment comment)
                {
                    // Якщо знайшли — повертаємо
                    if (comment.Id == id) return comment;
                    // Якщо ні — йдемо вглиб у відповіді цього коментаря
                    var found = FindCommentRecursive(comment.Replies, id);
                    if (found != null) return found;
                }
            }
            return null;
        }
Referenced by MiniBlogApp.Services.BlogStorage.AddReply(), and MiniBlogApp.Services.BlogStorage.FindCommentRecursive().
GetAllPosts() [1/2]
IEnumerable< Post > MiniBlogApp.Services.BlogStorage.GetAllPosts ()
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 125 of file BlogStorage.cs.
        {
            lock (_lock)
            {
                return Posts.OrderByDescending(p => p.CreatedAt).ToList();
            }
        }
Referenced by MiniBlogApp.Tests.ServiceTests.BlogStorageAddPostTests.AddPost_ShouldAddPostCorrectly().
GetAllPosts() [2/2]
IEnumerable< Post > MiniBlogApp.Services.BlogStorage.GetAllPosts (IPostSortStrategy sortStrategy)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 170 of file BlogStorage.cs.
        {
            lock (_lock)
            {
                var currentPosts = Posts.ToList();
                return sortStrategy.Sort(currentPosts).ToList();
            }
        }
GetPostById()
Post? MiniBlogApp.Services.BlogStorage.GetPostById (int id)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 143 of file BlogStorage.cs.
        {
            lock (_lock)
            {
                return GetPostByIdInternal(id);
            }
        }
Referenced by MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.AddComment_ShouldAddToPostAndLogMessage(), MiniBlogApp.Tests.ServiceTests.BlogStorageEdgeCaseTests.AddComment_ShouldHandleEmptyText(), MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.DeletePost_ShouldRemovePost(), and MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.UpdatePost_ShouldChangeContent().
GetPostByIdInternal()
Post? MiniBlogApp.Services.BlogStorage.GetPostByIdInternal (int id) private
Definition at line 165 of file BlogStorage.cs.
        {
            return Posts.FirstOrDefault(p => p.Id == id);
        }
Referenced by MiniBlogApp.Services.BlogStorage.AddComment(), MiniBlogApp.Services.BlogStorage.AddLike(), MiniBlogApp.Services.BlogStorage.AddReply(), MiniBlogApp.Services.BlogStorage.DeletePost(), MiniBlogApp.Services.BlogStorage.GetPostById(), MiniBlogApp.Services.BlogStorage.RemoveLike(), and MiniBlogApp.Services.BlogStorage.UpdatePost().
GetPostsByUser()
IEnumerable< Post > MiniBlogApp.Services.BlogStorage.GetPostsByUser (string username)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 133 of file BlogStorage.cs.
        {
            lock (_lock)
            {
                return Posts.Where(p => p.Author?.ToString() == username)
                            .OrderByDescending(p => p.CreatedAt)
                            .ToList();
            }
        }
RemoveLike()
void MiniBlogApp.Services.BlogStorage.RemoveLike (int postId, string username)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 178 of file BlogStorage.cs.
        {
            lock (_lock)
            {
                var post = GetPostByIdInternal(postId);
                if (post == null) return;
                var like = post.Likes.FirstOrDefault(l => l.Username == username);
                if (like != null)
                {
                    post.Likes.Remove(like);
                }
            }
        }
UpdatePost()
Post? MiniBlogApp.Services.BlogStorage.UpdatePost (int id, string title, string content)
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 100 of file BlogStorage.cs.
        {
            lock (_lock)
            {
                var post = GetPostByIdInternal(id);
                if (post != null)
                {
                    post.Title = title;
                    post.Content = content;
                    return post;
                }
                return null;
            }
        }
Referenced by MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.UpdatePost_ShouldChangeContent(), and MiniBlogApp.Tests.ServiceTests.BlogStorageEdgeCaseTests.UpdatePost_ShouldFailGracefully_WhenPostDoesNotExist().
Member Data Documentation
_lock
readonly object MiniBlogApp.Services.BlogStorage._lock = new object() private
Definition at line 18 of file BlogStorage.cs.
Referenced by MiniBlogApp.Services.BlogStorage.AddComment(), MiniBlogApp.Services.BlogStorage.AddLike(), MiniBlogApp.Services.BlogStorage.AddPost(), MiniBlogApp.Services.BlogStorage.AddReply(), MiniBlogApp.Services.BlogStorage.DeletePost(), MiniBlogApp.Services.BlogStorage.GetAllPosts(), MiniBlogApp.Services.BlogStorage.GetAllPosts(), MiniBlogApp.Services.BlogStorage.GetPostById(), MiniBlogApp.Services.BlogStorage.GetPostsByUser(), MiniBlogApp.Services.BlogStorage.RemoveLike(), and MiniBlogApp.Services.BlogStorage.UpdatePost().
_nextId
int MiniBlogApp.Services.BlogStorage._nextId = 1 private
Definition at line 19 of file BlogStorage.cs.
Referenced by MiniBlogApp.Services.BlogStorage.AddComment(), MiniBlogApp.Services.BlogStorage.AddPost(), and MiniBlogApp.Services.BlogStorage.AddReply().
Property Documentation
Posts
List<Post> MiniBlogApp.Services.BlogStorage.Posts = new() get
Implements MiniBlogApp.Services.IBlogStorage.
Definition at line 20 of file BlogStorage.cs.
{ get; } = new();
Referenced by MiniBlogApp.Tests.ServiceTests.BlogStorageAddLikeTests.AddLike_ShouldDoNothing_WhenPostDoesNotExist(), MiniBlogApp.Services.BlogStorage.AddPost(), MiniBlogApp.Tests.ServiceTests.BlogStorageAddLikeTests.BlogStorageAddLikeTests(), MiniBlogApp.Tests.ServiceTests.BlogStorageAddPostTests.BlogStorageAddPostTests(), MiniBlogApp.Tests.ServiceTests.BlogStorageAdvancedTests.BlogStorageAdvancedTests(), MiniBlogApp.Tests.ServiceTests.BlogStorageEdgeCaseTests.BlogStorageEdgeCaseTests(), MiniBlogApp.Services.BlogStorage.DeletePost(), MiniBlogApp.Services.BlogStorage.GetAllPosts(), MiniBlogApp.Services.BlogStorage.GetAllPosts(), MiniBlogApp.Services.BlogStorage.GetPostByIdInternal(), and MiniBlogApp.Services.BlogStorage.GetPostsByUser().
The documentation for this class was generated from the following file:
/home/runner/work/MiniBlogApp/MiniBlogApp/MiniBlogApp/Services/BlogStorage.cs