MiniBlogApp: MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests Class Reference
MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests Class Reference
Contains edge case tests for UserService.
Public Member Functions
void Authenticate_ShouldBeCaseSensitive ()
Tests case sensitivity in username authentication.
void Authenticate_ShouldFailForEmptyPassword ()
Tests authentication failure for empty passwords.
void GetAll_ShouldReturnAtLeastTwoUsers ()
Ensures GetAll() returns the expected number of users.
Private Attributes
readonly UserService _service = new()
Instance of the UserService under test.
Static Private Attributes
const string CorrectUsername = "serhii"
Valid username for authentication.
const string CorrectPassword = "1234"
Valid password for authentication.
const string WrongCaseUsername = "Serhii"
Username with different casing to test case sensitivity.
const string EmptyPassword = ""
Empty password string to test authentication failure.
const int MinimumUserCount = 2
Minimum number of users expected in the service.
Detailed Description
Contains edge case tests for UserService.
Verifies that the UserService correctly handles authentication and retrieval operations, ensuring robustness against improper input and checking the correctness of stored user data.
Definition at line 25 of file UserServiceAdvancedTests.cs.
Member Function Documentation
Authenticate_ShouldBeCaseSensitive()
void MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.Authenticate_ShouldBeCaseSensitive ()
Tests case sensitivity in username authentication.
Verifies that the authentication method rejects usernames that differ only in letter casing from the stored usernames. Ensures that "serhii" and "Serhii" are treated as distinct.
Definition at line 52 of file UserServiceAdvancedTests.cs.
        {
            var result = _service.Authenticate(WrongCaseUsername, CorrectPassword);
            Assert.Null(result);
        }
Authenticate_ShouldFailForEmptyPassword()
void MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.Authenticate_ShouldFailForEmptyPassword ()
Tests authentication failure for empty passwords.
Confirms that the service does not allow a user to log in with an empty password, even if the username exists in the predefined list. Ensures basic security against blank credentials.
Definition at line 65 of file UserServiceAdvancedTests.cs.
        {
            var result = _service.Authenticate(CorrectUsername, EmptyPassword);
            Assert.Null(result);
        }
GetAll_ShouldReturnAtLeastTwoUsers()
void MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.GetAll_ShouldReturnAtLeastTwoUsers ()
Ensures GetAll() returns the expected number of users.
Validates that the UserService contains at least the predefined users ("serhii" and "maria") and that the collection returned by GetAll() is consistent with the internal user list.
Definition at line 78 of file UserServiceAdvancedTests.cs.
        {
            Assert.True(_service.GetAll().Count() >= MinimumUserCount);
        }
Member Data Documentation
_service
readonly UserService MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests._service = new() private
Instance of the UserService under test.
Definition at line 28 of file UserServiceAdvancedTests.cs.
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.Authenticate_ShouldBeCaseSensitive(), MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.Authenticate_ShouldFailForEmptyPassword(), and MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.GetAll_ShouldReturnAtLeastTwoUsers().
CorrectPassword
const string MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.CorrectPassword = "1234" static private
Valid password for authentication.
Definition at line 34 of file UserServiceAdvancedTests.cs.
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.Authenticate_ShouldBeCaseSensitive().
CorrectUsername
const string MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.CorrectUsername = "serhii" static private
Valid username for authentication.
Definition at line 31 of file UserServiceAdvancedTests.cs.
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.Authenticate_ShouldFailForEmptyPassword().
EmptyPassword
const string MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.EmptyPassword = "" static private
Empty password string to test authentication failure.
Definition at line 40 of file UserServiceAdvancedTests.cs.
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.Authenticate_ShouldFailForEmptyPassword().
MinimumUserCount
const int MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.MinimumUserCount = 2 static private
Minimum number of users expected in the service.
Definition at line 43 of file UserServiceAdvancedTests.cs.
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.GetAll_ShouldReturnAtLeastTwoUsers().
WrongCaseUsername
const string MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.WrongCaseUsername = "Serhii" static private
Username with different casing to test case sensitivity.
Definition at line 37 of file UserServiceAdvancedTests.cs.
Referenced by MiniBlogApp.Tests.ServiceTests.UserServiceAdvancedTests.Authenticate_ShouldBeCaseSensitive().
The documentation for this class was generated from the following file:
/home/runner/work/MiniBlogApp/MiniBlogApp/MiniBlogApp.Tests/ServiceTests/UserServiceAdvancedTests.cs