MiniBlogApp: MiniBlogApp.Models.Comment Class Reference
MiniBlogApp.Models.Comment Class Reference
Клас коментаря, який реалізує патерн Composite.
Public Member Functions
void AddReply (ICommentComponent reply)
int GetTotalCount ()
Рекурсивно рахує кількість коментарів у цій гілці.
string Display (int indentLevel=0)
Повертає відформатований текст коментаря з урахуванням вкладеності (відступів).
Properties
int Id [get, set]
string Author = string.Empty [get, set]
string Text = string.Empty [get, set]
List< ICommentComponent > Replies = new List<ICommentComponent>() [get, set]
Detailed Description
Клас коментаря, який реалізує патерн Composite.
Він одночасно є і окремим об'єктом (коментарем), і контейнером для інших таких об'єктів (відповідей).
Definition at line 11 of file Comment.cs.
Member Function Documentation
AddReply()
void MiniBlogApp.Models.Comment.AddReply (ICommentComponent reply)
Definition at line 19 of file Comment.cs.
        {
            Replies.Add(reply);
        }
Display()
string MiniBlogApp.Models.Comment.Display (int indentLevel = 0)
Повертає відформатований текст коментаря з урахуванням вкладеності (відступів).
Implements MiniBlogApp.Composites.ICommentComponent.
Definition at line 38 of file Comment.cs.
        {
            string indent = new string('-', indentLevel * 2); // Створюємо відступ для візуалізації вкладеності
            var sb = new StringBuilder();
            sb.AppendLine($"{indent}> {Author}: {Text}");
            foreach (var reply in Replies)
            {
                // Рекурсивно викликаємо Display для всіх відповідей, збільшуючи рівень відступу
                sb.Append(reply.Display(indentLevel + 1));
            }
            return sb.ToString();
        }
GetTotalCount()
int MiniBlogApp.Models.Comment.GetTotalCount ()
Рекурсивно рахує кількість коментарів у цій гілці.
Implements MiniBlogApp.Composites.ICommentComponent.
Definition at line 25 of file Comment.cs.
        {
            int count = 1; // Рахуємо поточний коментар
            foreach (var reply in Replies)
            {
                count += reply.GetTotalCount(); // Магія патерну: рекурсивно рахуємо всі вкладені відповіді
            }
            return count;
        }
Property Documentation
Author
string MiniBlogApp.Models.Comment.Author = string.Empty get set
Definition at line 14 of file Comment.cs.
{ get; set; } = string.Empty;
Id
int MiniBlogApp.Models.Comment.Id get set
Definition at line 13 of file Comment.cs.
{ get; set; } // Додаємо ID
Replies
List<ICommentComponent> MiniBlogApp.Models.Comment.Replies = new List<ICommentComponent>() get set
Definition at line 16 of file Comment.cs.
{ get; set; } = new List<ICommentComponent>();
Referenced by MiniBlogApp.Models.Comment.AddReply(), MiniBlogApp.Models.Comment.Display(), and MiniBlogApp.Models.Comment.GetTotalCount().
Text
string MiniBlogApp.Models.Comment.Text = string.Empty get set
Definition at line 15 of file Comment.cs.
{ get; set; } = string.Empty;
The documentation for this class was generated from the following file:
/home/runner/work/MiniBlogApp/MiniBlogApp/MiniBlogApp/Models/Comment.cs