name: Generate and Deploy Doxygen Docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    # ЦЕЙ БЛОК ВАЖЛИВИЙ: дозволяємо боту записувати результати на сайт
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Doxygen and Graphviz
        run: sudo apt-get update && sudo apt-get install -y doxygen graphviz

      - name: Generate Doxygen documentation
        # Переконайся, що Doxyfile лежить у корені проєкту поруч із .sln
        run: doxygen Doxyfile

      - name: List files
        # Цей крок покаже нам у логах, де саме створилася папка (html чи docs/html)
        run: ls -R

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Якщо в Doxyfile ти не міняла налаштування, папка називається html
          publish_dir: ./html
